### ISSUE TITLE
show photos attached to events in the Media tab of the person under Photographs

### ISSUE THREAD

**Issue by darthdesi** [clsturgeon/MemoryKeeper#63]
Current behavior is that a photo attached to an event.. like Marriage.. only shows when the event tiddler is viewed. It also shows up under the Events tab of the person.

But it will be nice to also see the photo under Media->Photographs. 

Otherwise the workflow would be to : 
1) create Photograph tiddler.. reference Marriage photo.
2) create Event.. link Photograph tiddler

Can we automatically make the Event Photo into a Photograph tiddler too?

Side question: can 1 event (like Marriage) be associated with multiple Images / Photos?

**Comment by clsturgeon** [comment]
To answer the question. Yes. I have an marriage event with 10 photographs.

I'm not sure what you are asking. Do you want the user to select one of those photos, of the 10 in my case, shown on the Photograph tab of the marriage events, where the user can have that photo automatically assign to the image field of the marriage event? If so, not sure how the UI would work.

**Comment by darthdesi** [comment]
How do I attach multiple images to an event?

**Comment by clsturgeon** [comment]
There are two ways:

1. Most common... in edit mode of each photograph the user clicks "Select Events" and selects the marriage event. Therefore, in this case the user has to do it for each photo. 

2. Alternately, the user opens the marriage event in view mode. On the photograph tab click on the "bulk associate process" button. This expands to show all photographs in the system (that are not already associated with this event). The user filters the result list of photographs to locate all the marriage photos. For each found photo the users clicks on the "+" button in the table (first column) associated with the marriage photo. This automatically does what 1. did, but it does it for you. As the user clicks the plus button the photo is added to photograph tab of the event and removed from the bulk processing table.

This screenshot from my phone shows the button to expand the control to do bulk processing (it's the button on the top most-right) and the yellow background area is the expanded control to select photos. 

![image](https://github.com/user-attachments/assets/e9b7fc28-5823-4f81-9335-17704722ccea)

**Comment by clsturgeon** [comment]
This is not to be confused with the image field in the event. That is independent of photograph tiddlers.

This field is used as a primary image of the event and is shown in a few places including on timeline nodes.

There are tricks to show multiple images in the image field. It's not really a trick, just using TW wikitext to do it. I do this on source tiddlers. It too has an image field. 

Open this tiddler newspaper tiddler. 

https://clsturgeon.github.io/MemoryKeeper/#1902-05-22%20-%20Broke%20his%20neck

You'll see 2 images of the newspaper clipping. Then look at it in edit mode to see how it was done. 

This could be done in an event tiddler as well, but I have done it there--no need to I guess.

**Comment by darthdesi** [comment]
Thank you for the detailed instructions.. I'll file a separate issue for
you if the documentation is incomplete for the bulk associate feature.

Also regarding the main image for the event, the "issue" was that this
image is visible only in the event. It's not visible under Media or
Photographs. It would be nice if :
1) we can somehow make the main event photo into a Photograph to be listed
under Media-> Photographs
OR
2) we force Events to only choose main images from Photographs

**Comment by clsturgeon** [comment]
I assume you mean the image field in the event, which as I mentioned, is independent of photograph tiddlers. 

Photos listed under the Photograph tab are clickable to open them.  I think it would be confusing to add this image there. In fact what I do is typically select one of the photos or a source images to be shown here. Eg i want to show a newspaper headline as the image about the event.

**Comment by darthdesi** [comment]
I'm not following why it would be confusing for a user. Using an example from the public MK, ie https://clsturgeon.github.io/MemoryKeeper/#1898-02-08%20-%20Patent%20Filed%20-%20no%2059.113%20-%20Cover%20for%20Refrigerators

Now this patent photo is only seen if someone accidentally bumps into it while going through Events. Otherwise someone just browsing through Photographs will never discover it.

MK's design philosophy is very strong on linked associations between these various entities. A Photograph is an important entity in MK. 

Now interestingly there are 2 places to view images in MK... 
1) https://clsturgeon.github.io/MemoryKeeper/#Images (images have no visible relationships to the tiddler they are associated to, ie People or Events. When i open an image from #images, i can't see any People or Event links.)
2) https://clsturgeon.github.io/MemoryKeeper/#Photographs (photographs have relationships to People and Events)

Why have 2 different repositories for the same concept, ie an Image? Maybe we should remove the Image field from Person and Event, and force these entities to choose a Photograph. Then everything is discoverable.

I realize that removing the Image Field is probably not possible.. so please noodle a solution to make the #Images more discoverable and related to other entities.

**Comment by clsturgeon** [comment]
Your example of the patent cover is a good example. 

This is not a photograph. It's an image of a page (or part of a page) from the actual patent.

I purposely separated photographs and the use of the image field in other entities. Source entity also has an image field. This was designed to caption 1 or images of a source document. I did not want to force the user to create a photograph entry for each image. In fact the user can and should add images using the img tags in text and description fields, not just image fields. I do this when writing assertions/proof arguments to prove a point. A person tiddler also has an image field. It's typically used as a head shot of an image, which in typically do not include the photographs.

The photograph entity was design to be for photographs, in the traditional sense, where photo captions can be written.

However, I realize, as I've done it, an image field in an event could be the same image in a photograph tiddler.

If the user needs to find an image file, such as mypic.jpg, they can type that into the search function text box, and on the relevant tab it will show the tiddlers that reference it. 

The relevant tab is configured to search text, description, image and other fields.

Over last point. If the user wants an image field to reference an image field value in a photograph tiddler, this can be done, but they need to know TW WikiText to do it.

The syntax is 

`{{my-photograph-tiddler!!image}}`

Now having typed this, a button could be provided (next to the image field) where the user can select a photograph tiddler and MK automatically fills in the image field for them.

Now having typed that, a new photograph toolbar button could do this too to fill in this syntax in the text field. The description field could use this feature too.

**Comment by darthdesi** [comment]
yeah i see your point on when to use what. I like the suggestions of atleast providing the user with the option to link an existing Photograph into an event image / event description. And not have them remember TW syntax.

But in the case they do choose to use the Image field (like in the Patent example), could we create a new tiddler under Media that shows all images used in the image fields of other tiddlers, and also links to the containing tiddler? Maybe that will help in discovering the event/person that image is associated with?

**Comment by clsturgeon** [comment]
I might be up for an all media tab and a separate tiddler for a global list.

Here is another idea. Just do you know about it. This one I started to use but I personally abandon it. It is still available to use but I did not document it. 

This approach is actually a TiddlyWiki defined approach, not mine. ie TW approved. 

What the user does is create an Image Tiddler. In MK that this under Media-->Image/Icon. The user references the image, whether that be a photograph, a source document, whatever in this Image tiddler.

Then in those image fields in photographs, sources, person tiddlers, events, etc the user references the image tiddler. The syntax in the image field is simpler:

{{image-tiddler-name}}

Now all external images and internal images are in one place. 

Disadvantages:

- this takes longer to do
- user is challenged with more unique tiddler titles to create
- this bloats the html file. You are generating a new tiddler for every image in the system.

This was a showstopper for me and I abandon it. In fact I would not recommend it. Even thumbnail image references would go here bloating it even more.

**Comment by darthdesi** [comment]
The above assertion needs to be made into some murder mystery podcast :)

Ok i think i'm getting it.. images can be referenced in the image field, and inside the tiddler text/description fields.

1) Is it possible to write a search filter that pulls all [img[url]] tags from all the tiddlers, and Image source, render them in a list, and show the associated tiddler link?
2) is it possible to show which tiddlers are associated to the Media->Image/Icon photo? Ie when i view https://clsturgeon.github.io/MemoryKeeper/#adolphus , can we also search and list out the associated tiddler(s) using this image?

**Comment by clsturgeon** [comment]
1. Yes.  However, I'd like to use the pagination tool I wrote so the user can page through the results instead of scrolling through one huge list. This is a complex filter which does not work with my pagination tool... but I do have it.

![Image](https://github.com/user-attachments/assets/52836599-fd46-41d3-adce-25d0306bb74a)

2. I need to look into this. This is a TW tiddler, and I'd be messing with core toddlers.

**Comment by clsturgeon** [comment]
2. It was easy to do... how do you think the items should be listed, as it can have more than one?

![Image](https://github.com/user-attachments/assets/7be5e71b-5bb7-43af-aa86-f4cc87630ad0)

![Image](https://github.com/user-attachments/assets/c7f72c52-e1b9-4b2e-bae6-c4be7d1fc0c9)

**Comment by darthdesi** [comment]
awesome.. maybe below every image, just put a header for the list saying "referenced by:" so that end-user knows they can click on it and get to the tiddler using the image?

**Comment by clsturgeon** [comment]
Fixed: Item #2 is implemented in MK 1.0.02 rc2.

Item #1 is included in the new Pro Bundle Add-on 1.0.04

**Comment by darthdesi** [comment]
Hi @clsturgeon  fyi that your previous comment references issue numbers . Might get confusing later :)

I validated (2) ie Images/Icons now show which tiddlers reference them.

For (1), i download the ProBundle Add-on 1.0.04. I see the new menu item for "Referenced Images", but its not working.

I have an Event (dated of type marriage specifically if it matters) . In the "image" field, it has a reference to an external image via [img[pic-url]]. Event shows the referenced photo.. but photo and event do not appear under "referenced images".

**Comment by clsturgeon** [comment]
I haven't been near my computer for a bit. Check for please. You say you used 

[img[pic-url]]

Try

[img [pic-url]]

... let need know if that worked. If not, something else is going on.

**Comment by clsturgeon** [comment]
Actually, I don't think this list will work for all cases. 

There are so ways to reference an image:

`[img [file name/or image tiddler]]
{{ image tiddler }}
<$image source= "file name" />
<img src="file name"/>

<picture>
  <source media="(min-width: 650px)" srcset="img_food.jpg">
  <source media="(min-width: 465px)" srcset="img_car.jpg">
  <img src="img_girl.jpg">
</picture>`

**Comment by darthdesi** [comment]
nope i tried [img [file-url]] with the space after img.. but still not getting picked up.

I understand there are many ways to reference images.. but this one is specifically in the image field of the Event tiddler.

![Image](https://github.com/user-attachments/assets/716ed301-89b8-44c3-a321-4c0332e24513)

I hope you have the magic to search and list these out. :)

**Comment by clsturgeon** [comment]
There are two levels of an external image. 

1. [img[Motovun Jack.jpg]]
2. Your example with a url. That is a true external image. I don't think my query will find these. In your screen shot I can't see the file ext. my query looks for TW images, ie 1.  Not 2.

**Comment by darthdesi** [comment]
sorry if it feels like i'm pushing :) but would this help? https://talk.tiddlywiki.org/t/is-there-a-way-to-filter-tiddlers-based-on-field-value-alone-not-the-field-name/6023/5

So the filter essentially searches all tiddlers where the Image field has a value, and it extracts the value and creates a list with the embedded value. As the image field usually has wikitext like [img [url]], then the list should render?

My filter knowledge is zero else i would try :)

**Comment by clsturgeon** [comment]
What is the file ext of your image? This may be the problem. My filter only returns .jpg, .gif, .png

I can more options like .jpeg

**Comment by clsturgeon** [comment]
Correction... the filter is returning all instances of images found in the same field of the same tiddler. That is good news.

My assertion tiddler of Adolphus has two images when I view the assertion, but the Referenced Images tool only shows one.  Hence why I thought that it was not working.  However, in this case, the 2nd image is a transcluded tiddler of an image. It will not support that. Transcluded image means I referenced another tiddler, a photography tiddler, and I specified a template on how to show it.

**Comment by darthdesi** [comment]
thanks for working on this.. i think it will be a very useful feature to discover all the cross-references of images to tiddlers.

In my case, the external url link to Google Drive does not specify the image type in the url. The html rendered by the wikitext for [img [https://https://drive.google.com/thumbnail?sz=w1000&amp;id=xxxxxxxxxxxxxxxxxxx]] is:
<img src="https://drive.google.com/thumbnail?sz=w1000&amp;id=xxxxxxxxxxxxxxxxxxx" class=" tc-image-loaded">

Is it possible to not look for specific image extensions, but just render the value of the Image field of the tiddler.. if TW+browser can render it, then i'm hoping your list can too without worrying about the image extension type.

**Comment by clsturgeon** [comment]
Okay, that took all day to work out. Pro Bundle 1.0.05 has been changed. if you downloadeded it before, just download it again:

https://github.com/clsturgeon/MemoryKeeper/blob/master/docs/support/downloads/Pro%20Bundle-addon-1.0.05.json

The problem is a very complex filter that uses a very complex regular expression to match strings in the text.  About an hour ago I went to phind.com and asked the AI engine for the regular expression. It was good, but not perfect. 

This tiddler's pagination acts differently than a standard pagination. Eg. On the Events, if I have it configured to show 10 at a time, that is what I get. The pagination for the referenced images is hard-coded to show 6 "tiddlers"; NOT 6 images. Therefore, each page will have 6 tiddlers, but because a tiddler could have more than 1 image, there will be more rows shown. 

For those tiddlers with more than 1 image found, the tiddler TITLE text is prefixed with multiple dots/periods for all the rows except the first for that tiddler.

**Comment by darthdesi** [comment]
you da man!

Downloaded and imported Probundle1.0.05. 

First load of "referenced images" did nothing... I clicked around the various other drop downs. Nothing. 
Clicked back to Images, and boom a bunch of results loaded!!!! Maybe it was running in the background and took some time to complete..? If yes, is there a concept of putting a progressbar, or a text saying "waiting for results..".

Couple of issues:
1) it found the image i had referenced in my event's image field. But the thumbnail in the 3rd column is not clickable to magnify (is it called Spotlight in MK)? But if go to the event, and click on the image in the event box, that nicely magnifies.
2) Search results in my MK says :

(whats wrong with Github now.. it wont upload images)

**Comment by clsturgeon** [comment]
1. The image does not have links on it, just the title. Not sure spotlight would work here. 

2. This suggests the filter found 11 tiddlers, but the inner filter, which walks through each tiddler is not finding any. It means the regular expression is finding more than it should. I would need see those tiddlers. 

I have a free GitHub account. May be we hit a disk space limit?

**Comment by darthdesi** [comment]
someone else in github is also complaining right now about image uploads failing.. i don't think its a repo limit. Couldn't find any docs suggesting that there are limits to what size Issues can be..

**Comment by darthdesi** [comment]
> 2. This suggests the filter found 11 tiddlers, but the inner filter, which walks through each tiddler is not finding any. It means the regular expression is finding more than it should. I would need see those tiddlers.

Other than my Event, there are the other 3 tiddlers containing an image according to the results.

Media	TableOfContents$:/tags/mk	
People	TableOfContents$:/tags/mk	
Research	TableOfContents$:/tags/mk	

Not sure why the total says 11...

**Comment by darthdesi** [comment]
i'm surprised (with my lack of TW knowledge) that we need a regex for this.. atleast for the Image field, there is no need for regex's right? its a straight copy of the value in the field into the search list, if not empty?

**Comment by clsturgeon** [comment]
When you have a single img in the image field you are properly correct. I have image fields with numerous img tokens. 

I'm not on my laptop, so I can't test this. On my phone I found a good regular expression validator. 

Do you want to try this? Open the Referenced Image tiddler. Look for the <$let widget. One of variables in there is lengthy regular expression string. Change the value to this very simple string. 

`\[img(.*?)\[(.*?)\]\]`

Save and test.

**Comment by darthdesi** [comment]
`<$let
	imgfilex="\.(jpg|png|gif|jpeg|JPG|PNG|GIF)"
imgfile="\[img(.*?)\[(.*?)\]\]"`

seems to be working. Still getting 11 tiddlers.

My first dive into MK code.. soon i'll be fixing these for you if i begin to comprehend all the JS.

**Comment by clsturgeon** [comment]
I thought this would only return 4 tiddlers. Do u see 11 tiddlers with proper results, 6 tiddlers on the first page, 5 more on the 2nd page?

**Comment by darthdesi** [comment]
Nope still same as before.. 4 in first page.. nothing in second page.

![Image](https://github.com/user-attachments/assets/4708fa93-774c-4a81-83e5-00a43c31b881)

![Image](https://github.com/user-attachments/assets/62090d74-992c-473b-a2b0-f3fca8165b8a)

**Comment by clsturgeon** [comment]
Thanks. Yeah, it looks like the outer filter found 11 tiddlers, the inner filter ignored 7 of them. Can you compare the syntax used in image field the first tiddler (that was reported) against other tiddlers (that were not reported) where you know you populated the image field. What's the difference? Did you use the img token differently?

**Comment by clsturgeon** [comment]
Okay, download probundle 1.0.05 again.... I will not provide any instructions. See if my onscreen instructions work for you.

**Comment by darthdesi** [comment]
imported the latest ProBundle 1.0.5.
Clicked Referenced Images.
Greeted by this error text :
`Found 7 unsupported usage of the IMG token. tiddlers listed have [img[ usage in the image field. Change the usage to: [img [`

i'm confused why a space is necessary between [img and the next inner [ . TW docs don't insist on it:
https://tiddlywiki.com/static/Images%2520in%2520WikiText.html

```
Images can be included in [WikiText](https://tiddlywiki.com/static/WikiText.html) with the following syntax:

[img[Motovun Jack.jpg]]
[img[https://tiddlywiki.com/favicon.ico]]
```

**Comment by darthdesi** [comment]
to continue the experiment, i edited one of the 7 tiddlers identified where i'm using an [img[url]] wikitext. to [img [url]]
Now the search results returns 6. But i'm not seeing any image previews of the 1 fixed.
Is there more to come? :)

**Comment by darthdesi** [comment]
also the only tiddlers scanned for the [img[]] tag appears to be only Person ones. All 7 in my case were tagged Person. 

The Event tiddler with the referenced image didn't show up in the result.

**Comment by clsturgeon** [comment]
It's true TW does not require it. However, at one point it did. I know this will not work `[img class=myclass[myfile.jpg]]` in TW. With that I always put the space in. 

The code to get this to work needs the space. I can change the code to get that to work, but then all the other options fail. It does not support both. I spent time trying, but gave up. I might be able to solve with JS. 

I have already spent way too much time on this. I'm afraid I'm not seeing the value. But that is me. When I need these special tools. I type in search criteria in the search filter tab. 

This tiddler already has too many limitations, eg not supporting html img or tw image widget. 

So, to solve this properly I would rewrite it in JS and address all the limitations, but this will take time. I'm have been trying to write GEDCOM import/export for the past 2 years; this will take priority.

**Comment by darthdesi** [comment]
also Craig, similar to how you fixed the back reference to tiddlers using Image/Icons, can you please add the same backreference to Media->Photographs, ie show which tiddlers are using them?

**Comment by clsturgeon** [comment]
I'm not following any of your comments. From my testing the Referenced images tiddler will:

 * block you from seeing any results if it sees any img usage with that space character. This is of course based on the field selection. Ie it may work for description field, but block you for image field.
* this issue with the space has nothing to do with what field is searched. ie all fields need the space. Changing it to only support image field does nothing. 
* referenced images is not dependant on how any tiddler is tagged. 
* I do not understand the last post. Referenced Images looks at fields, such as the image field, no matter how it is tagged. So photograph tiddlers are included as they use the image field. Having said that, they fail to see photo maps because they use html img instead of wikitext img.

**Comment by clsturgeon** [comment]
I stumbled upon a TW filter on TW community forum last night that might solve the space issue.  It has, so this has been corrected, and the error check is no longer needed. The tiddler now supports `[img[myfile.jpg]`.

In addition, the search box was enhanced to search the image field. This enables me to find all my .gif file references in the image field.

**Comment by darthdesi** [comment]
validated in pro-bundle 1.0.5 that [img [url]] works.

Awesome fix Craig!
